

<style type="text/css">
.scroll {
  height:900px;
  overflow-y: scroll;
}
 </style>
 
<div class="container">
    <h5 class="card-text">What is Imported Products Revenue?</h5>  
       <div class="scroll">
           <div class="main" id="section1"
           <!--Wizard Tab-1 Help  Starts-->              
               <p>Generally <b>Products Revenue</b> is nothing more than revenue generated by selling a range of products, and
                 is the total amount of revenue received by the company for products sold for a specific period of time.
                  <br/>
                  <br/>Typically, Department stores, mens, ladies, and children's boutiques, and many other retailers sell products at the stores or online. 
                  </p>
                <h5 class=" card-text pt-1">For example:</h5>  
               <p>                                
                  Shireen Serina has her own skin care company  and Chanelle Ellana is an inspirational  writer, both are  selling their products to small boutiques,
                  and at their online stores at https://www.moaks.com and https://www.totheheartandback.com 
               </p>
               <table border="0" width="100%" cellspacing="10" cellpadding="5" class="table table-responsive table-striped">
                <thead>
                <tr>
                    <th>Question</th>
                    <th>Assumption</th>
                </tr>
                </thead>
                    <tbody>       
                        <tr>
                            <td>How many items do you plan to sell each month?</td>
                            <td>1,000 items</td>
                        </tr>
                        <tr>
                            <td>What is the average selling price</td>
                            <td>$100.00</td>
                        </tr>
                        <tr>
                         <td>What is the average cost of goods  </b></td>
                         <td>$30.00 <b>&nbsp;&nbsp;(30% of selling Price)</td><hr>
                        </tr>
                        <tr>
                            <td>What is is my projected gross profit? </b></td>
                            <td>$70.00 <b>&nbsp;&nbsp;(Selling Price - Cost of goods)</td>
                        </tr>
                    </tbody>
                </table>
            <hr style="border-top: 3px solid #0064B2; background: transparent;">    
            <h5>How do I add a Product?</h5>
                <div class="row p-5">    
                    <ol>
                        <li>From the amin dashboard click Got to Products.</li>

                        <div class="row p-5">
                            <div class="shadow-lg p-5 mb-5 bg-white rounded">
                            <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_1.png" width="90%" height="90%"alt="Startup-1" class="img-responsive p-4"></center>           
                            </div>
                        </div>

                        <li> Click <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-plus"></i> Add Products</button> </li>  
                       
                        
                         <div class="row p-5">
                            <div class="shadow-lg p-5 mb-5 bg-white rounded">
                            <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_2.png" width="90%" height="90%"alt="Startup-1" class="img-responsive p-4"></center>           
                            </div>
                        </div>
                    </ol>
                </div>
            
            <hr style="border-top: 3px solid #0064B2; background: transparent;">    
            <!--====================================   tab 1 starts  ========================-->
            
            <h5>Tab 1 - Products </h5>
               <div class="row p-5">    
                    <ol>
                        <li>Upload an image of the product (Optional).</li>
                        <li>Select your preferred method, Local or Imported Products.</li>
                        <li>If imported is selected, from the drop down dialog, select your interest rate.</li>
                        <li>Enter you're projected monthly unit sales.</li>
                        <li>Enter an average unit cost.</li>       

                    <div class="row p-5">
                        <div class="shadow-lg p-5 mb-5 bg-white rounded">
                        <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_3.png" width="90%" height="90%"alt="Startup-1" class="img-responsive p-4"></center>           
                    </div>
                </div>

                <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-arrow-right"></i> Next</button> when your done.</li>
                </ol>  
            </div>
            <hr style="border-top: 3px solid #0064B2; background: transparent;">    
           
        </div> <!-- /.main -->
    </div> <!-- /.scroll -->
</div> <!-- /.container -->

