
<style type="text/css">
.scroll {
  height:900px;
  overflow-y: scroll;
}
 </style>
 
 <div class="container">
    <h4>What is a Profit and Loss Statement (P&L)?</h4>
    <div class="scroll">
      <div class="main" id="section1">
        <hr style="border-top: 3px solid #0064B2; background: transparent;">
            <p>The P&L statement is one of three financial statements every public company issues quarterly and annually, along with the balance sheet and the cash flow statement. 
                It is often the most popular and common financial statement in a business plan as it quickly shows how much profit or loss was generated by a business.
            </p>
            <h6><b>KEY TAKEAWAYS</b></h6>
             <ul>
                <li>The P&L statement is a financial statement that summarizes the revenues, costs, and expenses incurred during a specified period.</li><br>
                <li>The P&L statement is one of three financial statements every public company issues quarterly and annually, along with the balance sheet and the cash flow statement.</li><br>
                <li>It is important to compare P&L statements from different accounting periods, as the changes in revenues, operating costs, R&D spending, and net earnings over time are more meaningful than the numbers themselves.</li><br>
                <li>Together with the balance sheet and cash flow statement, the P&L statement provides an in-depth look at a company's financial performance..</li>  
             </ul>
            <hr style="border-top: 3px solid #0064B2; background: transparent;">
            <center><img src="<?= asset_url(); ?>img/help_screen_shots/reports/profit_loss.png" width="100%" height="100%"alt="Key Ratios" class="img-responsive"></center>     
        </div> <!-- /.main -->
    </div> <!-- /.scroll -->
</div> <!-- /.container -->


