

<style type="text/css">
    .scroll {
	height:900px;
	overflow-y: scroll;
    }
</style>

<div class="container">
    <h5 class="card-text">1. What is Products Revenue?</h5>
    <div class="scroll">
	<div class="main" id="section1">

	    <p>
		Generally <b>Products Revenue</b> is nothing more than revenue generated by selling a range of products, and
		is the total amount of revenue received by the company for products sold for a specific period of time.
		<br/>
		<br/>Typically, Department stores, mens, ladies, and children's boutiques, and many other retailers sell products at the stores or online.
	    </p>
	    <h5 class=" card-text pt-1">For example:</h5>
	    <p>
		Shireen Serina has her own skin care company  and Chanelle Ellana is an inspirational  writer, both are  selling their products to small boutiques,
		and at their online stores at https://www.moaks.com and https://www.totheheartandback.com
	    </p>
	    <table border="0" width="100%" cellspacing="10" cellpadding="5" class="table table-responsive table-striped">
                <thead>
		    <tr>
			<th>Question</th>
			<th>Assumption</th>
		    </tr>
                </thead>
		<tbody>
		    <tr>
			<td>How many items do you plan to sell each month?</td>
			<td>1,000 items</td>
		    </tr>
		    <tr>
			<td>What is the average selling price</td>
			<td>$100.00</td>
		    </tr>
		    <tr>
			<td>What is the average cost of goods  </b></td>
			<td>$30.00 <b>&nbsp;&nbsp;(30% of selling Price)</td><hr>
		</tr>
		<tr>
		    <td>What is is my projected gross profit? </b></td>
		    <td>$70.00 <b>&nbsp;&nbsp;(Selling Price - Cost of goods)</td>
		</tr>
		</tbody>
	    </table>
            <hr style="border-top: 3px solid #0064B2; background: transparent;">

            <h5>How do I add a Product?</h5>
	    <div class="row p-5">
		<ol>
		    <li>From the main Dashboard click <a class="btn btn-outline-primary">Go to Products <span class="fa fa-arrow-right"></span></a></li>

		    <div class="row p-5">
			<div class="shadow-lg p-5 mb-5 bg-white rounded">
                            <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_1.png" width="90%" height="90%"alt="Startup-1" class="img-responsive p-4"></center>
			</div>
		    </div>

		    <li> Click <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-plus"></i> Add Products</button> </li>

		    <div class="row p-5">
			<div class="shadow-lg p-5 mb-5 bg-white rounded">
                            <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_2.png" width="90%" height="90%"alt="Startup-1" class="img-responsive p-4"></center>
			</div>
		    </div>


		    <li>Upload an image of the product (Optional).</li>
		    <li>Select your preferred method, Local or Imported Products.</li>
		    <li>If imported is selected, from the drop down dialog, select your interest rate.</li>
		    <li>Enter you're projected monthly unit sales.</li>
		    <li>Enter an average unit cost.</li>

                    <div class="row p-5">
                        <div class="shadow-lg p-5 mb-5 bg-white rounded">
			    <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_3.png" width="90%" height="90%"alt="Startup-1" class="img-responsive p-4"></center>
                        </div>
                    </div>

		    <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-arrow-right"></i> Next</button> when your done.</li>
                </ol>
            </div>




            <hr style="border-top: 3px solid #0064B2; background: transparent;">

        </div> <!-- /.main -->

	<!--====================================   tab 2 starts  ========================-->
	<div class="container">
	    <h5>2. Monthly Unit Sales</h5>

	    <div class="main" id="section1"

		 <div class="row p-5">
		<ol>
		    <li>Enter opening stock qty (optional).</li>
		    <li>Click the manual button If you want to add monthly unit sales by months, or accept the monthly average qty for each month.</li>
		    <div class="row p-1">
			<div class="shadow-lg p-5 mb-5 bg-white rounded">
			    <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_4.png" width="100%" height="100%"alt="Startup-1" class="img-responsive p-4"></center>
			</div>
		    </div>

		    <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-arrow-right"></i> Next</button> when your done.</li>
		</ol>
	    </div>
	    <hr style="border-top: 3px solid #0064B2; background: transparent;">


	</div> <!-- /.container -->
	<!--====================================   tab 3 starts  ========================-->
	<div class="container">
	    <h5>3.  BOM (Bill of Materials)</h5>

	    <div class="main" id="section1"

		 <h5>What is BOM?</h5>

		<p>BOM is the sum of direct costs required to produce a product. Direct costs include:</P>

		<ul>
		    <li>materials;</li>
		    <li>labour; </li>
		    <li>transaction costs; and sometimes </li>
		    <li>a portion of your fixed costs (like hosting fees for a business that sells software). </li>
		</ul>

		<p>
		    It can be useful to calculate the average cost to produce your products.
		    This tells you the cost to produce one unit of your product, also known as your marginal cost.
		    Your marginal cost can be used to calculate your gross margin.
		</p>

		<h5 class="pt-1">Key Takeaways</h5>
		<p>
		    Accurately measuring your COGS allows you to calculate your gross profit margin. Understanding your gross margin provides a
		    powerful tool for assessing the potential of your business to grow profitably.
		    Businesses should work to reduce their COGS before pouring money into sales and marketing.
		    This will ensure that you get to keep a larger proportion of the revenues you collect from new customers.
		</p>
		<hr style="border-top: 3px solid #0064B2; background: transparent;">
		<h5 class="pt-1">Whats next?</h5>
		<div class="row p-5">
		    <ol>
			<li>Upload an image of the product (Optional or use the default image.</li>
			<li>Select your preferred method, Local or Imported Products.</li>
			<li>If imported is selected, from the drop down dialog, select your interest rate.</li>
			<li>Enter you're projected monthly unit sales.</li>
			<li>Enter an average unit cost.</li>
			<li> Click <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-plus"></i> Add Row</button></li>

			<div class="row p-1">
			    <div class="shadow-lg p-5 mb-5 bg-white rounded">
				<center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_5.png" width="100%" height="100%"alt="Startup-1" class="img-responsive p-4"></center>
			    </div>
			</div>

			<li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-arrow-right"></i> Next</button> when your done.</li>
		    </ol>
		</div>
		<hr style="border-top: 3px solid #0064B2; background: transparent;">
	    </div> <!-- /.main -->

	</div> <!-- /.container -->
	<!--====================================   tab 4 starts  ========================-->
	<div class="container">
	    <h5>4.  Markup Summary</h5>

	    <div class="main" id="section1">
		<p>
		    The price you charge for your product can be the difference between success or failure. Early stage businesses have slim (and often negative) margins.
		    A small percentage change in price can be the difference between reaching your goal and objectives or simply running out of cash .
		</p>

		<p>
		    Markup is the ratio between the cost of a goods or services and its selling price.
		    A % markup is added onto the total cost incurred by the product or service in order to cover the costs of goods or services ,
		    and operating expenses in order to create a profit.
		</p>

		<h5 class="pt-1">Key Takeaways</h5>
		<p>
		    Pricing is as important to your business as it is a key ingredient in generating recurring sales. Your pricing should reflect your product, your customers,
		    your cost structure and your competitors.
		    Reviewing your pricing on a regular, as well as comparing your markup to your competitor's can help you in finding right price for your product.
		</p>

		<hr style="border-top: 3px solid #0064B2; background: transparent;">
		<h5 class="pt-1">Whats next?</h5>
		<ol>
		    <li>Upload an image of the product (Optional).</li>
		    <li>Select your preferred method, Local or Imported Products.</li>
		    <li>If imported is selected, from the drop down dialog, select your interest rate.</li>
		    <li>Enter you're projected monthly unit sales.</li>
		    <li>Enter an average unit cost.</li>

		    <div class="row p-1">
			<div class="shadow-lg p-5 mb-5 bg-white rounded">
			    <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_6.png" width="100%" height="100%"alt="Startup-1" class="img-responsive p-4"></center>
			</div>
		    </div>


		    <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-save"></i> Save</button> when your done.</li>
		</ol>

		<!--====================================   save dialog starts  ========================-->
		<h5>Save</h5>
		<ol>
		    <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-check"></i> Yes</button> to add an image of the product.</li>
		    <li>Click  <button type='button' id="" class='btn btn-outline-primary' name='next' value='Next' ><i class="fa fa-eraser"></i> No</button> to use the default image.</li>
		    <center><img src="<?= asset_url(); ?>img/help_screen_shots/revenue/local_product/localPro_7.png" width="100%" height="100%"alt="Startup-12" class="img-responsive p-4"></center>
		    <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-save"></i> Save</button> when your done.</li>
		</ol>
		<hr style="border-top: 3px solid #0064B2; background: transparent;">
	    </div> <!-- /.main -->

	</div> <!-- /.container -->

    </div> <!-- /.scroll -->
</div> <!-- /.container -->
