
 

<h4 class="card-text">What is Service Revenue?</h4>  

    <p>Generally <b>Service Revenue</b> is nothing more than revenue generated by providing a service, and
        is the total amount of revenue received by the company for services rendered for a specific period of time.Personal Services Income (PSI) is income
        mainly derived from an individual’s personal efforts and skill.
        <br/>
        <br/>Typically, consultants and contractors who operate as a sole trader or work through a
        company,that charges fees on an hourly basis or a fixed job rate are classified as service
        industries.</p>
        <h4 class=" card-text pt-1">For example:</h4>  
    <p>                                
        Brock has a removalist business operating as a sole trader, he charges $120 per hour to move your goods from
        one place to another, he also charges $50 for call out fee, or quotation.
    </p>
    <h5 class="pt-3">Now what?</h5>
    <ol class="">
        <li>From the first drop list , select an industry.</li>
        <li>From the second drop list , select a rate option.</li>
        <li>Enter how many hours you will work.</li>       
        <li>Enter the rate you will charge.</li>   
        <li>Enter any additional charges.</li>
        <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-save"></i> Save</button> when your done.</li>
    </ol>
     
    <h5 class=" card-text pt-1">For example:</h5>  
    <p>                                
        Shireen Serina has her own skin care company  and Chanelle Ellana is an inspirational  writer, both are  selling their products to small boutiques,
        and at their online stores at https://www.moaks.com and https://www.totheheartandback.com 
    </p>
    
