

            <h5 class="card-text">1. What is Products Revenue?</h5>  
    
               <p>
		        Generally <b>Products Revenue</b> is nothing more than revenue generated by selling a range of products, and
                 is the total amount of revenue received by the company for products sold for a specific period of time.
                  <br/>
                  <br/>Typically, Department stores, mens, ladies, and children's boutiques, and many other retailers sell products at the stores or online. 
                  </p>
                <h5 class=" card-text pt-1">For example:</h5>  
               <p>                                
                  Shireen Serina has her own skin care company  and Chanelle Ellana is an inspirational  writer, both are  selling their products to small boutiques,
                  and at their online stores at https://www.moaks.com and https://www.totheheartandback.com 
               </p>

               <table  width="100%" cellspacing="10" cellpadding="5" class="table table-responsive table-striped">
                <thead>
                <tr>
                    <th>Question</th>
                    <th>Assumption</th>
                </tr>
                </thead>
                    <tbody>       
                        <tr>
                            <td>How many items do you plan to sell each month?</td>
                            <td>10 items</td>
                        </tr>
                        <tr>
                            <td>What is the average selling price</td>
                            <td>$100.00</td>
                        </tr>
                        <tr>
                         <td>What is the average cost of goods  </b></td>
                         <td>$30.00 <b>&nbsp;&nbsp;(30% of selling Price)</td><hr>
                        </tr>
                        <tr>
                            <td>What is is my projected gross profit? </b></td>
                            <td>$70.00 <b>&nbsp;&nbsp;(Selling Price - Cost of goods)</td>
                        </tr>
                    </tbody>
                </table>
                
                <table  cellspacing="0" cellpadding="0" width="576" style="width: 431.75pt; border-collapse: collapse; border: none;">
                <tbody>
                    <tr>
                        <td valign="top" style="width: 98.75pt; border: 1pt solid windowtext; padding: 0in 5.4pt;">
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><strong>Number of Journals sold weekly</strong></p>
                        </td>
                        <td valign="top" style="width: 99pt; border-style: solid solid solid none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0in 5.4pt;">
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><strong>Price per journal</strong></p>
                        </td>
                        <td valign="top" style="width: 1.5in; border-style: solid solid solid none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0in 5.4pt;">
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><strong>Total Weekly Revenue</strong></p>
                        </td>
                        <td valign="top" style="width: 1.75in; border-style: solid solid solid none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0in 5.4pt;">
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><strong>Total Yearly Revenue</strong></p>
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><strong>(52 weeks)</strong></p>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top" style="width: 98.75pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0in 5.4pt;">
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><em>10</em></p>
                        </td>
                        <td valign="top" style="width: 99pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0in 5.4pt;">
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><em>$100</em></p>
                        </td>
                        <td valign="top" style="width: 1.5in; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0in 5.4pt;">
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><em>10 x $100 = $1,000</em></p>
                        </td>
                        <td valign="top" style="width: 1.75in; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0in 5.4pt;">
                        <p style="margin: 6pt 0in; vertical-align: baseline;"><em>1,000 x 52 = $52,000</em></p>
                        </td>
                    </tr>
                </tbody>
            </table>

            <ol class=" pt-3">
                <li><strong>Sale of physical product</strong>: The customer pays in cash for the product (for example, pumpkins, books, furniture…) and the customer is then free do whatever she or he wants with it.</li>
                <li><strong>Usage fee</strong>: The customer pays a user fee for a particular service, such as water, phone, hotel room, etc. As such, the amount paid by the customer depend on how much of the service is being used (for example, how many liters of water, how many nights at the hotel, how many calls etc.)</li>
                <li><strong>Subscription fee</strong>: The customer pays, for example, once a month, or yearly, for a particular service. For example, sports/gym facilities often use this option. Even if you do not use it, you pay. This could also work for products. You have your customers pay an amount to you every month and in return you deliver your product on a regular basis.</li>
                <li><strong>Lending/renting/leasing</strong>: This Revenue Stream grants someone the right to use a particular product for a fixed period of time in return for a fee. This method can be used for rentals of cars, rentals of farm machinery etc.</li>
                <li><strong>Brokerage fees:</strong> Through this Revenue Stream, your company gets its revenue from an intermediate service. This method is often used by real estate agents (earning a commission every time they match the buyer and seller) and credit card providers (getting a percentage of the value of each sale completed between the merchant and the customer).</li>
                <li><strong>Advertising:</strong> Your business may charge fees for advertising a product, service or brand. For example, newspapers and media often rely on this method.</li>
                <li><strong>Volume and unit selling</strong>: Your company charges a fixed price for a product. However, if the customer choses to buy your product in higher quantities, they could get a discount (either by a lower price or additional products). You can have different prices and discounts for different Customer Segments. For example, to encourage large purchases of pumpkins, you give 2 free pumpkins to every customer who buys more than 50 pumpkins.</li>
            </ol>

            <hr style="border-top: 1px solid #0064B2; background: transparent;">    
            
            <h5>How do I add a Product?</h5>
                <div class="row p-5">    
                    <ol>
                      <li>From the main Dashboard click <a class="btn btn-outline-primary">Go to Products <span class="fa fa-arrow-right"></span></a></li>

                        <div class="row p-5">
                            <div class="shadow-lg p-5 mb-5 bg-white rounded">
                        
                                       
                            </div>
                        </div>

                        <li> Click <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-plus"></i> Add Products</button> </li>  
            
                         <div class="row p-5">
                            <div class="shadow-lg p-5 mb-5 bg-white rounded">
                         
        
                            </div>
                        </div>
        
      
                        <li>Upload an image of the product (Optional).</li>
                        <li>Select your preferred method, Local or Imported Products.</li>
                        <li>If imported is selected, from the drop down dialog, select your interest rate.</li>
                        <li>Enter you're projected monthly unit sales.</li>
                        <li>Enter an average unit cost.</li>       

                    <div class="row p-5">
                        <div class="shadow-lg p-5 mb-5 bg-white rounded">
                          
                        </div>
                    </div>

                <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-arrow-right"></i> Next</button> when your done.</li>
                </ol>  
            </div>
                
        
           
                <h5>2. Monthly Unit Sales</h5>
         
               
                    <div class="row p-5">    
                        <ol>
                            <li>Enter opening stock qty (optional).</li>
                            <li>Click the manual button If you want to add monthly unit sales by months, or accept the monthly average qty for each month.</li> 
                            <div class="row p-1">
                                <div class="shadow-lg p-5 mb-5 bg-white rounded">
                    
                                

                                </div>
                            </div>

                            <li>Click  <button type='button' id="" class='btn btn-outline-success' name='next' value='Next' ><i class="fa fa-arrow-right"></i> Next</button> when your done.</li>
                        </ol>
                    </div>
            
            
                <h5>3.  BOM (Bill of Materials)</h5>
            
        

                <h5>What is BOM?</h5>
                    
                <p>BOM is the sum of direct costs required to produce a product. Direct costs include:</P>

                <ul>
                    <li>materials;</li>
                    <li>labour; </li>
                    <li>transaction costs; and sometimes </li>
                    <li>a portion of your fixed costs (like hosting fees for a business that sells software). </li>
                    </ul>
                
                    <p>
                        It can be useful to calculate the average cost to produce your products. 
                        This tells you the cost to produce one unit of your product, also known as your marginal cost.
                        Your marginal cost can be used to calculate your gross margin.
                    </p>
                    
                    <h5 class="pt-1">Key Takeaways</h5>
                    <p>
                        Accurately measuring your COGS allows you to calculate your gross profit margin. Understanding your gross margin provides a 
                        powerful tool for assessing the potential of your business to grow profitably. 
                        Businesses should work to reduce their COGS before pouring money into sales and marketing. 
                        This will ensure that you get to keep a larger proportion of the revenues you collect from new customers.
                    </p>
           
            
                    <h5>4.  Markup Summary</h5>

 
        
                    <p>
                        The price you charge for your product can be the difference between success or failure. Early stage businesses have slim (and often negative) margins. 
                        A small percentage change in price can be the difference between reaching your goal and objectives or simply running out of cash .
                    </p>
                    
                    <p>
                        Markup is the ratio between the cost of a goods or services and its selling price. 
                        A % markup is added onto the total cost incurred by the product or service in order to cover the costs of goods or services ,
                        and operating expenses in order to create a profit.
                    </p>

                    <h5 class="pt-1">Key Takeaways</h5>
                    <p>
                        Pricing is as important to your business as it is a key ingredient in generating recurring sales. Your pricing should reflect your product, your customers, 
                        your cost structure and your competitors.
                        Reviewing your pricing on a regular, as well as comparing your markup to your competitor's can help you in finding right price for your product.
                    </p>

