

    <!-- ===============================================-->
    <!--   Wizard Service Revenue  Tab 2 Content Details-->
    <!-- ===============================================-->      
            
    <div class="tab-pane " role="tabpanel" aria-labelledby="bootstrap-wizard-tab2" id="bootstrap-wizard-tab2">
       
        <form novalidate="novalidate">  
            <div class="card mb-1 mb-lg-0">
                <div class="card-header">
                    <div class="row">
                        <div class="col-lg-6">
                            <a class="mb-0 d-block d-flex align-items-center" href="#ser-form"  onclick="add_service()" id="btnSer" data-bs-toggle="collapse" aria-expanded="false" aria-controls="ser-form">
                            <span class="circle-dashed"><span class="fas fa-plus"></span></span><span class="ms-3"></span></a>
                        </div><!-- /.col-->
                        <div class="col-lg-6">
                        <a class="btn btn-falcon-outline-info float-end text-primary" data-html="true" data-bs-placement="auto" data-popover-content="#ser" data-toggle="popover" data-trigger="focus" href="#" tabindex="0"><i class="fa fa-info-circle" aria-hidden="true" ></i></a>
                    </div><!-- /.col-->
                </div><!-- /.row-->
           
            </div><!-- /.header-->


            <!-- ===============================================-->
            <!--   Popover -->
            <!-- ===============================================-->    

            <div class="p-2">              
                <div class="hidden d-none" id="ser">    
                    <div class="popover-heading"><span><img src='<?php echo site_url(); ?>custom-assets/img/favicons/favicon-16x16.png'/></span> 
                        Help Center
                    </div>
                        <div class="popover-body">
                            
                            <div class="card mb-3">
                                <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<?php echo site_url(); ?>custom-assets/img/icons/spot-illustrations/corner-4.png);"></div> <!--/.bg-holder-->
                                    <div class="card-body position-relative">
                                        <div class="row">
                                            <div class="col-lg-12">  

                                                <h5 class="pt-1">What are your service projection?</h5>   

                                                <p class="mt-1 ps-3 mb-3">
                                                    Generally Service Revenue is nothing more than revenue generated by providing a service and charging anf hourly or fixed jon rate. 
                                                    Some Typical companies are as follows:
                                                </p>
                                                <ul class="pt-1">
                                                    <li>carpenters</li>
                                                    <li>plumbers</li>
                                                    <li>accountants</li>
                                                    <li>solicitors</li>          
                                                </ul>
                                                <hr style="border-top: 3px solid #0064B2; background: transparent;"> 
                                                <h5>How do I add a service?</h5>
                                                <ol class="pt-1">      
                                                    <li>Click the + button</li>                                    
                                                    <li>Select a role full or part time?</li>
                                                    <li>Enter the number of people</li>
                                                    <li>Enter the weekly hours</li>     
                                                    <li>Enter the hourly pay rate</li>
                                                    <li>AuziPlan will do the calculation for you.</li>
                                                    <li><a class="btn btn-falcon-success btn-sm me-1 mb-1 float-start" type="button"><i class="far fa-save fa-1x" aria-hidden="true"></i>  Save and Continue</a></li>
                                                </ol><!-- /.ol -->                              
                                            </div>
                                        </div><!-- /.co 12-->
                                    </div><!-- /.row-->
                                </div><!-- /.card body-->
                            </div><!-- /.bg holder-->
                        </div><!-- /.card-->	
                    </div><!-- /.popover body-->



                <!-- ===============================================-->
                <!--   Card for Test Input Boxes  -->
                <!-- ===============================================-->     
               
                        
                            <div class="collapse" id="ser-form">
                                <div id="ser">

                                    <div class="container" >                 
                                        <div class="row">
                                            <p class="mt-2">                            
                                                    The page header is a nice little feature to add appropriate spacing around the headings on a page. 
                                                    This is particularly helpful on a web page where you may have several post titles and need a way to add distinction to each of them.            
                                                </p>   
                                                <div class="container">
                                                    <div class="row">
                                                        <div class="col-sm">
                                                            <div class="form-floating mb-3">
                                                            <select name="industry" class="form-select" id="industry" aria-label="Industry">
                                                                <option selected>Select Industry</option>
                                                                <option value="Administration">Administration</option>

                                                                <!--------------------------------------------------------------------
                                                                [1. Online Revenue is turned on for Basic subscription]
                                                                ---------------------------------------------------------------------->
                                                                <option <?php ($industry == 'Accounting') ? print "selected" : print "" ?>>Accounting</option>
                                                                <option <?php ($industry == 'Automotive electrical services') ? print "selected" : print "" ?>>Automotive electrical services</option>
                                                                <option <?php ($industry == 'Architectural services') ? print "selected" : print ""; ?>>Architectural services</option>
                                                                <option <?php ($industry == 'Alarm installation services – fire and security') ? print "selected" : print "" ?>>Alarm installation services – fire and security</option>
                                                                <option <?php ($industry == 'Air conditioning, refrigeration and heating services') ? print "selected" : print "" ?>>Air conditioning, refrigeration and heating services</option>
                                                                <option <?php ($industry == 'Building Construction') ? print "selected" : print "" ?>>Building Construction</option>

                                                                <option <?php ($industry == 'Bottle shops and liquor retailing') ? print "selected" : print ""; ?>>Bottle shops and liquor retailing</option>
                                                                <option <?php ($industry == 'Bricklaying services') ? print "selected" : print "" ?>>Bricklaying services</option>

                                                                <option <?php ($industry == 'Book retailing') ? print "selected" : print "" ?>>Book retailing</option>
                                                                <option <?php ($industry == 'Blocklaying services') ? print "selected" : print ""; ?>>Bricklaying services</option>
                                                                <option <?php ($industry == 'Beauty services') ? print "selected" : print "" ?>>Beauty services</option>

                                                                <option <?php ($industry == 'Barber and men’s hairdressing') ? print "selected" : print "" ?>>Barber and men’s hairdressing</option>
                                                                <option <?php ($industry == 'Bakeries and hot bread shops') ? print "selected" : print ""; ?>>Bakeries and hot bread shops</option>
                                                                <option <?php ($industry == 'Beauty services') ? print "selected" : print "" ?>>Beauty services</option>

                                                                <option <?php ($industry == 'Cabinet makers') ? print "selected" : print "" ?>>Cabinet makers</option>
                                                                <option <?php ($industry == 'Cake shops and patisseries') ? print "selected" : print ""; ?>>Cake shops and patisseries</option>
                                                                <option <?php ($industry == 'Carpet laying services') ? print "selected" : print "" ?>>Carpet laying services</option>
                                                                <option <?php ($industry == 'Capentry service') ? print "selected" : print "" ?>>Carpentry service</option>
                                                                <option <?php ($industry == 'Carpet laying services') ? print "selected" : print "" ?>>Carpet laying services</option>
                                                                <option <?php ($industry == 'Catering services') ? print "selected" : print "" ?>>Cabinet makers</option>

                                                                <option <?php ($industry == 'Cement rendering') ? print "selected" : print ""; ?>>Cement rendering</option>
                                                                <option <?php ($industry == 'Chicken shops') ? print "selected" : print "" ?>>Chicken shops</option>
                                                                <option <?php ($industry == 'Child care services') ? print "selected" : print "" ?>>Child care services</option>
                                                                <option <?php ($industry == 'Chiropractic and osteopathic services') ? print "selected" : print "" ?>>Chiropractic and osteopathic services</option>
                                                                <option <?php ($industry == 'Cleaning services – building and other industrial') ? print "selected" : print "" ?>>Cleaning services – building and other industrial</option>
                                                                <option <?php ($industry == 'Cleaning services – carpet, rug and furniture upholstery') ? print "selected" : print "" ?>>Cleaning services – carpet, rug and furniture upholstery</option>
                                                                <option <?php ($industry == 'Clothing') ? print "selected" : print "" ?>>Clothing</option>
                                                                <option <?php ($industry == 'Coffee shops') ? print "selected" : print ""; ?>>Coffee shops</option>
                                                                <option <?php ($industry == 'Computer retailing') ? print "selected" : print "" ?>>Computer retailing</option>
                                                                <option <?php ($industry == 'Concreting services') ? print "selected" : print "" ?>>Concreting services</option>
                                                                <option <?php ($industry == 'Confectionery retailing') ? print "selected" : print "" ?>>Confectionery retailing</option>
                                                                <option <?php ($industry == 'Courier services') ? print "selected" : print "" ?>>Courier services</option>
                                                                <option <?php ($industry == 'Cosmetics') ? print "selected" : print "" ?>>Cosmetics</option>
                                                                <option <?php ($industry == 'Craft shops') ? print "selected" : print ""; ?>>Craft shops</option>

                                                                <option <?php ($industry == 'Delivery services') ? print "selected" : print "" ?>>Delivery services</option>
                                                                <option <?php ($industry == 'Dental specialists') ? print "selected" : print "" ?>>Dental specialists</option>
                                                                <option <?php ($industry == 'Dental surgeons – general') ? print "selected" : print ""; ?>>Dental surgeons – general</option>
                                                                <option <?php ($industry == 'Discount and variety stores') ? print "selected" : print "" ?>>Discount and variety stores</option>
                                                                <option <?php ($industry == 'Domestic appliance repair and maintenance') ? print "selected" : print "" ?>>Domestic appliance repair and maintenance</option>
                                                                <option <?php ($industry == 'Driving schools and instructors') ? print "selected" : print ""; ?>>Driving schools and instructors</option>
                                                                <option <?php ($industry == 'Delicatessen') ? print "selected" : print ""; ?>>Delicatessen</option>

                                                                <option <?php ($industry == 'Electrical and electronic product retailing') ? print "selected" : print "" ?>>Electrical and electronic product retailing</option>
                                                                <option <?php ($industry == 'Electrical services') ? print "selected" : print "" ?>>Electrical services</option>
                                                                <option <?php ($industry == 'Entertainment media retailing') ? print "selected" : print "" ?>>Entertainment media retailing</option>

                                                                <option <?php ($industry == 'Fence construction') ? print "selected" : print ""; ?>>Fence constructionl</option>
                                                                <option <?php ($industry == 'Fish and chips shops') ? print "selected" : print "" ?>>Fish and chips shops</option>
                                                                <option <?php ($industry == 'Fish and seafood retailing – fresh') ? print "selected" : print "" ?>>Fish and seafood retailing – fresh</option>
                                                                <option <?php ($industry == 'Floor covering retailing') ? print "selected" : print "" ?>>Floor covering retailing</option>
                                                                <option <?php ($industry == 'Florists') ? print "selected" : print ""; ?>>Florists</option>
                                                                <option <?php ($industry == 'Footwear retailing') ? print "selected" : print ""; ?>>Footwear retailing</option>
                                                                <option <?php ($industry == 'Fruit and vegetable retailing') ? print "selected" : print "" ?>>Fruit and vegetable retailing</option>
                                                                <option <?php ($industry == 'Fuel retailing') ? print "selected" : print "" ?>>Fuel retailing</option>
                                                                <option <?php ($industry == 'Furniture removalists') ? print "selected" : print "" ?>>Furniture removalists</option>
                                                                <option <?php ($industry == 'Furniture retailing') ? print "selected" : print ""; ?>>Furniture retailing</option>

                                                                <option <?php ($industry == 'Graphic Artist') ? print "selected" : print "" ?>>Graphic Artist</option>
                                                                <option <?php ($industry == 'Garden supplies retailing') ? print "selected" : print ""; ?>>Garden supplies retailing</option>
                                                                <option <?php ($industry == 'Gift stores') ? print "selected" : print "" ?>>Gift stores</option>
                                                                <option <?php ($industry == 'Glazing services') ? print "selected" : print "" ?>>Glazing services</option>
                                                                <option <?php ($industry == 'Grocery retailing and convenience stores') ? print "selected" : print "" ?>>Grocery retailing and convenience stores</option>


                                                                <option <?php ($industry == 'Hairdressers') ? print "selected" : print "" ?>>Hairdressers</option>
                                                                <option <?php ($industry == 'Hardware and building supplies retailing') ? print "selected" : print ""; ?>>Hardware and building supplies retailing</option>
                                                                <option <?php ($industry == 'Health and fitness centres') ? print "selected" : print "" ?>>Health and fitness centres</option>
                                                                <option <?php ($industry == 'Health food retailing') ? print "selected" : print "" ?>>Health food retailing</option>
                                                                <option <?php ($industry == 'Homewares retailing') ? print "selected" : print "" ?>>Homewares retailing</option>

                                                                <option <?php ($industry == 'Ice cream retailing') ? print "selected" : print ""; ?>>Ice cream retailing</option>
                                                                <option <?php ($industry == 'It') ? print "selected" : print "" ?>>It</option>

                                                                <option <?php ($industry == 'Kebab shops') ? print "selected" : print "" ?>>Kebab shops</option>

                                                                <option <?php ($industry == 'Landscape construction') ? print "selected" : print ""; ?>>Landscape construction</option>
                                                                <option <?php ($industry == 'Laundry and dry-cleaning services') ? print "selected" : print "" ?>>Laundry and dry-cleaning services</option>
                                                                <option <?php ($industry == 'Lawn mower retailing') ? print "selected" : print "" ?>>Lawn mower retailing</option>
                                                                <option <?php ($industry == 'Lawn mowing and garden services') ? print "selected" : print "" ?>>Lawn mowing and garden services</option>

                                                                <option <?php ($industry == 'Machinery and equipment repairs and maintenance') ? print "selected" : print "" ?>>Machinery and equipment repairs and maintenance</option>
                                                                <option <?php ($industry == 'Manchester and other textile goods retailing') ? print "selected" : print ""; ?>>Manchester and other textile goods retailing</option>
                                                                <option <?php ($industry == 'Meat and poultry retailing – fresh') ? print "selected" : print "" ?>>Meat and poultry retailing – fresh</option>
                                                                <option <?php ($industry == 'Motor vehicle parts and batteries retailing') ? print "selected" : print "" ?>>Motor vehicle parts and batteries retailing</option>
                                                                <option <?php ($industry == 'Motor vehicle retail – new and used') ? print "selected" : print "" ?>>GMotor vehicle retail – new and used</option>
                                                                <option <?php ($industry == 'Musical instruments retail') ? print "selected" : print ""; ?>>Musical instruments retail</option>

                                                                <option <?php ($industry == 'Newsagents') ? print "selected" : print "" ?>>Newsagents</option>

                                                                <option <?php ($industry == 'Painting services') ? print "selected" : print ""; ?>>Painting services</option>
                                                                <option <?php ($industry == 'Panel beating and smash repairs') ? print "selected" : print "" ?>>Panel beating and smash repairs</option>
                                                                <option <?php ($industry == 'Pest control services') ? print "selected" : print "" ?>>Pest control services</option>
                                                                <option <?php ($industry == 'Pets and pet supply retailing') ? print "selected" : print "" ?>>Pets and pet supply retailing</option>
                                                                <option <?php ($industry == 'Pharmacy') ? print "selected" : print ""; ?>>Pharmacy</option>
                                                                <option <?php ($industry == 'Physiotherapy services') ? print "selected" : print ""; ?>>Physiotherapy services</option>
                                                                <option <?php ($industry == 'Picture framing retailing') ? print "selected" : print "" ?>>Picture framing retailing</option>
                                                                <option <?php ($industry == 'Pizza shops – takeaway') ? print "selected" : print "" ?>>Pizza shops – takeaway</option>
                                                                <option <?php ($industry == 'Plastering and ceiling services') ? print "selected" : print "" ?>>Plastering and ceiling services</option>
                                                                <option <?php ($industry == 'Plumbing services') ? print "selected" : print ""; ?>>Plumbing services</option>
                                                                <option <?php ($industry == 'Printing') ? print "selected" : print ""; ?>>Printing</option>
                                                                <option <?php ($industry == 'Printing support services') ? print "selected" : print "" ?>>Printing support services</option>
                                                                <option <?php ($industry == 'Pubs, taverns and bars') ? print "selected" : print "" ?>>Pubs, taverns and bars</option>

                                                                <option <?php ($industry == 'Restaurants') ? print "selected" : print "" ?>>Restaurants</option>
                                                                <option <?php ($industry == 'Road freight transport services') ? print "selected" : print ""; ?>>Road freight transport services</option>
                                                                <option <?php ($industry == 'Roofing services, including roof tiling, guttering and metal roofing') ? print "selected" : print ""; ?>>Roofing services, including roof tiling, guttering and metal roofing</option>


                                                                <option <?php ($industry == 'Sports, camping and fishing retailing') ? print "selected" : print "" ?>>Sports, camping and fishing retailing</option>
                                                                <option <?php ($industry == 'Sports and physical recreation instruction') ? print "selected" : print ""; ?>>Sports and physical recreation instruction</option>
                                                                <option <?php ($industry == 'Stationery goods retailing') ? print "selected" : print ""; ?>>Stationery goods retailing</option>

                                                                <option <?php ($industry == 'Takeaway food services') ? print "selected" : print "" ?>>Takeaway food services</option>
                                                                <option <?php ($industry == 'Taxi drivers and operators') ? print "selected" : print ""; ?>>Taxi drivers and operators</option>
                                                                <option <?php ($industry == 'Tiling services – floor and wall') ? print "selected" : print ""; ?>>Tiling services – floor and wall</option>
                                                                <option <?php ($industry == 'Timber floor sanding') ? print "selected" : print "" ?>>Timber floor sanding</option>
                                                                <option <?php ($industry == 'Tobacco retailing') ? print "selected" : print ""; ?>>Tobacco retailing</option>
                                                                <option <?php ($industry == 'Towing services') ? print "selected" : print ""; ?>>Towing services</option>
                                                                <option <?php ($industry == 'Toy and game retailingd') ? print "selected" : print "" ?>>Toy and game retailing</option>
                                                                <option <?php ($industry == 'Tutoring and coaching') ? print "selected" : print ""; ?>>Tutoring and coaching</option>
                                                                <option <?php ($industry == 'Tyre retailing') ? print "selected" : print ""; ?>>Tyre retailing</option>

                                                                <option <?php ($industry == 'Veterinary services') ? print "selected" : print "" ?>>Veterinary services</option>
                                                                <option <?php ($industry == 'Video and other electronic media rental and hiring') ? print "selected" : print ""; ?>>Video and other electronic media rental and hiring</option>

                                                                <option <?php ($industry == 'Watch and jewellery retailing') ? print "selected" : print ""; ?>>Watch and jewellery retailing</option>

                                                                <!------------------------------------------------------------------------>
                                                            </select><!-- /.select -->
                                                            </div><!-- /.form-floating -->

                                                            <div class="form-floating mb-3">
                                                            <select name="rate" class="form-select" id="rate" aria-label="purpose">
                                                                <option selected>Select Rate</option>
                                                                <option value="hourly-rate">Hourly Rate</option>
                                                                <option value="fix-job-rate">Fix Job Rate</option>
                                                            </select><!-- /.select-->
                                                        </div><!-- /.form-floating -->
                                                            <?php /*
                                                            <div class="form-floating mb-3">
                                                            <input type="text" name="impser_hrswork"  class="form-control" id="impser_hrswork" placeholder="Price Per Share" value="<?= ($row->max_view) ? $row->max_view : '' ?>">
                                                            <label for="impser_hrswork">What is the percentage cost of services?</label>
                                                            </div><!-- /.form-floating -->

                                                            */ ?>
                                                        </div><!-- /.col -->

                                                        <div class="col-sm">
                                                            <div class="form-floating mb-3">
                                                                <input type="text" name="impser_hrswork"  class="form-control" id="impser_hrswork" placeholder="Price Per Share" value="<?= ($row->max_view) ? $row->max_view : '' ?>">
                                                                <label for="impser_hrswork">How many hours will you work on this job?</label>
                                                            </div><!-- /.form-floating -->

                                                            <div class="form-floating mb-3">
                                                                <input type="text"  name="impser_rateperhr"  class="form-control currencySign" id="impser_rateperhr" placeholder="Price Per Share" value="<?= ($row->max_view) ? $row->max_view : '' ?>">
                                                                <label for="impser_rateperhr">How much will you charge for this job?</label>
                                                            </div><!-- /.form-floating -->

                                                            <?php /*
                                                                <div class="form-floating mb-3">
                                                                <input type="text"  name="impser_callourfee"  class="form-control currencySign" id="impser_callourfee" placeholder="Price Per Share" value="<?= ($row->max_view) ? $row->max_view : '' ?>">
                                                                <label for="impser_callourfee">What other fee will you charge?</label>
                                                                </div><!-- /.form-floating -->
                                                            */ ?>
                                                        </div>   <!-- /.col -->
                                                    </div><!-- /.row -->
                                                </div> <!-- /.container -->
                                            </div><!-- /.row -->
                                        </div> <!-- /.container -->





                                        
                                    </div><!-- ./row -->                  
                                    <div class="row p-3">
                                                <div class="border-dashed-bottom my-3"></div>
                                        <div class="col-12 col-sm-12 offset-0 pt-3">
                                            <button class="btn btn-falcon-danger" type="button" id="btncancelservice" ><i class="far fa-window-close"></i> Cancel</button>
                                            <button type="button" id="btnSaveImport" class="btn  btn-falcon-success float-end" value="<?php echo $i + 1; ?>"><i class="fa fa-save"></i> Save and Continue</button>
                                        </div>
                                    </div>
                                </div>
                                
                            </form>
                    </div>
                    <!-- ===============================================-->
                    <!--  Result Tables-->
                    <!-- ===============================================-->      

                    <div class="box-body pt-3">
                        <div class="box-body table_one">
                            <div class="row" id="one_time_cost_row_add">

                                    <div class="col-lg-12 col-md-12 col-sm-12" id="one_time_cost_plant_equipment" style='margin-top: 16px;'>
                                        <div id="tableExample2" data-list='{"page":1,"pagination":true}'>
                                            <div class="table-responsive scrollbar">
                                                <div class="fixTableHead">

                                                    
                                                    <table id="monthly_expenseDT" class="table table-striped fs--1 mb-0" style="width:100%">
                                                        <thead class="bg-200 text-900">
                                                            <tr>             
                                                                <th>Industry</th>
                                                                <th>Rate/Job</th>  
                                                                <th>Hours Worked</th>    
                                                                <th>Hour Rate Charged</th>                                               
                                                                <th>Monthly Revenue</th>  
                                                                <th>Year 1</th>
                                                                <th>Year 2</th>
                                                                <th>Year 3</th>
                                                                <th>Action</th>
                                                            </tr>
                                                        </thead><!-- /.table header -->  
                                                            <tbody>
                                                        </tbody><!-- /.table body -->  
                                                            <tfoot>
                                                                <tr>                                                      
                                                                    <th></th>
                                                                    <th></th>
                                                                    <th></th>
                                                                    <th></th>
                                                                    <th></th> 
                                                                    <th></th>
                                                                    <th></th>
                                                                    <th></th>
                                                                    <th></th>                                  
                                                                </tr><!-- /.table row -->  
                                                        </tfoot><!-- /.table footer -->  
                                                    </table><!-- /.table -->  

                                                </div><!-- /.table fixed head -->  
                                            </div><!-- /.table sroll -->  
                                        </div><!-- /.table example 2 -->  
                                    </div><!-- /.col-12 -->  
                                </div>
                            </div>      
        
                        <div class="mb-3" style="display:none">
                            <label class="form-label" for="bootstrap-wizard-wizard-email">Email*</label>
                            <input class="form-control" type="email" name="email" placeholder="Email address" pattern="^([a-zA-Z0-9_.-])+@(([a-zA-Z0-9-])+.)+([a-zA-Z0-9]{2,4})+$" required="required" id="bootstrap-wizard-wizard-email" data-wizard-validate-email="true" />
                            <div class="invalid-feedback">You must add email</div>
                        </div>
                    </div>                        
                </div>

               

