

        <h5 class="card-text">What is Products Revenue?</h5>  

           <!--Wizard Tab-1 Help  Starts-->              
               <p>Generally <b>Products Revenue</b> is nothing more than revenue generated by selling a range of products, and
                 is the total amount of revenue received by the company for products sold for a specific period of time.
                  <br/>
                  <br/>Typically, Department stores, mens, ladies, and children's boutiques, and many other retailers sell products at the stores or online. 
                  </p>
                <h5 class=" card-text pt-1">For example:</h5>  
               <p>                                
                  Shireen Serina has her own skin care company  and Chanelle Ellana is an inspirational  writer, both are  selling their products to small boutiques,
                  and at their online stores at https://www.moaks.com and https://www.totheheartandback.com 
               </p>
               <table  width="100%" cellspacing="10" cellpadding="5" class="table table-responsive table-striped">
                <thead>
                <tr>
                    <th>Question</th>
                    <th>Assumption</th>
                </tr>
                </thead>
                    <tbody>       
                        <tr>
                            <td>How many items do you plan to sell each month?</td>
                            <td>1,000 items</td>
                        </tr>
                        <tr>
                            <td>What is the average selling price</td>
                            <td>$100.00</td>
                        </tr>
                        <tr>
                         <td>What is the average cost of goods  </b></td>
                         <td>$30.00 <b>&nbsp;&nbsp;(30% of selling Price)</td><hr>
                        </tr>
                        <tr>
                            <td>What is is my projected gross profit? </b></td>
                            <td>$70.00 <b>&nbsp;&nbsp;(Selling Price - Cost of goods)</td>
                        </tr>
                    </tbody>
                </table>
        



                
    
    